[book]
authors = ["David Krasnitsky"]
language = "en"
multilingual = false
src = "src"
title = "The Rust Offline Book"
description = "Manuals for establishing an offline environment for development in the Rust programming language."